parallel-jobs = 1
patches-source = "ReVanced/revanced-patches"
cli-source = "ReVanced/revanced-cli"

[Messenger]
enabled = true
build-mode = "apk"
arch = "arm64-v8a"
version = "auto"
uptodown-dlurl = "https://facebook-messenger.en.uptodown.com/android"
excluded-patches = "'Hide inbox subtabs' 'Disable typing indicator'"
